/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never;
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      never
    >;
    '/articles': RouteRecordInfo<
      '/articles',
      '/articles',
      Record<never, never>,
      Record<never, never>,
      | '/articles/'
      | '/articles/language-core/closure'
      | '/articles/language-core/scope'
      | '/articles/placeholder'
      | '/articles/test'
    >;
    '/articles/': RouteRecordInfo<
      '/articles/',
      '/articles',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/articles/language-core/closure': RouteRecordInfo<
      '/articles/language-core/closure',
      '/articles/language-core/closure',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/articles/language-core/scope': RouteRecordInfo<
      '/articles/language-core/scope',
      '/articles/language-core/scope',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/articles/placeholder': RouteRecordInfo<
      '/articles/placeholder',
      '/articles/placeholder',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/articles/test': RouteRecordInfo<
      '/articles/test',
      '/articles/test',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      never
    >;
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/';
      views: never;
    };
    'src/pages/[...all].vue': {
      routes: '/[...all]';
      views: never;
    };
    'src/pages/articles.vue': {
      routes:
        | '/articles'
        | '/articles/'
        | '/articles/language-core/closure'
        | '/articles/language-core/scope'
        | '/articles/placeholder'
        | '/articles/test';
      views: 'default';
    };
    'src/pages/articles/index.vue': {
      routes: '/articles/';
      views: never;
    };
    'src/pages/articles/language-core/closure.md': {
      routes: '/articles/language-core/closure';
      views: never;
    };
    'src/pages/articles/language-core/scope.md': {
      routes: '/articles/language-core/scope';
      views: never;
    };
    'src/pages/articles/placeholder.vue': {
      routes: '/articles/placeholder';
      views: never;
    };
    'src/pages/articles/test.md': {
      routes: '/articles/test';
      views: never;
    };
    'src/pages/login.vue': {
      routes: '/login';
      views: never;
    };
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap;
}

export {};
